name: py3.8
channels:
  - http://mirrors.aliyun.com/anaconda/pkgs/msys2
  - http://mirrors.aliyun.com/anaconda/pkgs/r
  - http://mirrors.aliyun.com/anaconda/pkgs/main
  - defaults
dependencies:
  - blas=1.0=openblas
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - ca-certificates=2023.01.10=hca03da5_0
  - certifi=2022.12.7=py38hca03da5_0
  - contourpy=1.0.5=py38h525c30c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.1=h80987f9_3
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - jpeg=9e=h80987f9_1
  - kiwisolver=1.4.4=py38h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_0
  - libffi=3.4.2=hca03da5_6
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.0=h313beb8_2
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - matplotlib=3.7.1=py38hca03da5_1
  - matplotlib-base=3.7.1=py38h78102c4_1
  - munkres=1.1.4=py_0
  - ncurses=6.4=h313beb8_0
  - numpy=1.23.5=py38h1398885_0
  - numpy-base=1.23.5=py38h90707a3_0
  - openssl=1.1.1t=h1a28f6b_0
  - packaging=23.0=py38hca03da5_0
  - pillow=9.4.0=py38h313beb8_0
  - pip=23.0.1=py38hca03da5_0
  - pyparsing=3.0.9=py38hca03da5_0
  - python=3.8.16=hc0d8a6c_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - readline=8.2=h1a28f6b_0
  - setuptools=65.6.3=py38hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.2=py38h1a28f6b_0
  - wheel=0.38.4=py38hca03da5_0
  - xz=5.2.10=h80987f9_1
  - zipp=3.11.0=py38hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.2=h8574219_0
  - pip:
      - akshare==1.9.23
prefix: /Users/wangzengjian/miniconda3/envs/py3.8
